In [33]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.utils import shuffle
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt
from google.colab import drive

In [34]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [35]:
df = pd.read_csv('/content/drive/MyDrive/http_requests.csv', sep=',', error_bad_lines=False, index_col=False, dtype='unicode')
df = shuffle(df)
df['payload'] = df['payload'].fillna(0)
df['payload'] = df['payload'].apply(lambda x: str(x))
df.drop(columns=['index', 'method', 'url', 'protocol', 'userAgent', 'pragma', 'cacheControl', 'accept', 'acceptEncoding', 'acceptCharset', 'acceptLanguage', 'host', 'connection', 'contentLength', 'contentType', 'cookie'], inplace=True)

In [36]:
# Function to generate a 255 dim feature vector from 'payload'
# Return a list of length 255 with features of payloads mapped to it
# Each list index represents an ASCII character and value represents count
# q = [4, 5, 2, 6, 12,  ....]


def vectorize_payload(payload):
    vec_255 = [0]*255
    vectorizer = CountVectorizer(analyzer='char', ngram_range=(1, 1))
    vectorized = vectorizer.fit_transform([payload])
    mapped = list(zip(vectorizer.get_feature_names(), vectorized.sum(0).getA1()))
    for x in mapped:
        vec_255[ord(x[0])] = x[1]
    return vec_255


In [37]:
# conversion to 256 dimensional vector
vectors = np.array(df['payload'].apply(lambda x: vectorize_payload(x)))
vectors


array([list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 3, 0, 0, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
       list([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 

In [38]:
# Function to generate frequency for 255 dim feature vectors
# Return a list of length 255 with feature frequencies
# Each list index represents an ASCII character and value represents its frequency
# q = [0.23, 0, 0, 0.03, 0.42,  ....] = 1


def calc_frequency(payloads_vectors):
    features_total = 0
    for feature in payloads_vectors:
        features_total += feature
    features_total *= 1.0
    payloads_vectors = [(x/features_total) for x in payloads_vectors]
    return np.array(payloads_vectors, dtype=np.float16)


results = [calc_frequency(x) for x in vectors]
features_frequency = np.vstack(results)
del results


In [39]:
# Function to generate mean vector for n payloads
# Assuming data set has traffic of n packets
# Return a list of length 255 with mean for every 255 features from payload vectors
# x' = [2.3, 3.1, 2.23, 7.5, 12.2,  ....]


def calc_mean(frequency_vectors):
    return np.mean(frequency_vectors, axis=0)


features_mean = calc_mean(features_frequency)


In [40]:
# Function to generate sample covariance matrix n-1
# Assuming data set has traffic of n packets
# Return a covariance matrix for given frequency vectors


def calc_cov_mat():
    mean_shift = np.transpose(np.subtract(features_frequency, features_mean))    
    return np.cov(mean_shift), mean_shift


cov_mat, mean_shift = calc_cov_mat()


In [9]:
eig_val, eig_vec = np.linalg.eigh(cov_mat)
eig_pairs = [(np.abs(eig_val[x]), eig_vec[:,x], x) for x in range(len(eig_val))]


In [ ]:
# Sort eig_pairs if need be
eig_pairs.sort(key=lambda x: x[0], reverse=True)
for i in eig_pairs:
    print(i[0])


In [ ]:
def scatter_plot_data():
    idx = np.argsort(eig_val)[::-1]
    evecs = eig_vec[:,idx]
    evecs = evecs[:, :2]
    
    data_resc = np.dot(evecs.T, mean_shift).T
    
    # scatter plot for data correlation
    clr1 = '#2026B2'
    fig2 = plt.figure(figsize=(20, 20))
    ax1 = fig2.add_subplot(111)
    ax1.plot(data_resc[:, 0], data_resc[:, 1], '.', mfc=clr1, mec=clr1)
    plt.show()


scatter_plot_data()


Tier 2

Cumulative Energy Test via Eig Vals and Vecs

In [ ]:
# Function to sum eigen vals which is equal to the cumulative energy
# Takes into account for a range of eigen values to count for
# Returns a single number representing the sum


def sum_cumulative_energy(pairs):
    THRESHOLD = 100e-6
    sum = 0
    for x in pairs:
        sum += x[0] if x[0] > THRESHOLD else 0
    return sum


cumulative_sum = sum_cumulative_energy(eig_pairs)
cumulative_sum


0.1611124834441891

In [ ]:
# This method goes through ordered eig_pairs and calculates cumsum
# If diff of cumsum with previous is less than threshold 155e-6
# It stops when cumsum is minimum to ensure maximum cumulative energy
# and minimum PC's
# It then returns the num of eigen values that can be used as PC


def cumulative_constant(cumulative_sum, pairs, cumulative_threshold=99.5):
    current_sum, curr_cumsum = 0, 0
    i = 0
    pc = []
    while i != len(pairs)-1 and curr_cumsum < cumulative_threshold:
        # print(pairs[i][2])
        current_sum += pairs[i][0]
        curr_cumsum = (current_sum/cumulative_sum)*100
        print("Current Sum: %f, Curr cumsum: %f" % (current_sum, curr_cumsum))
        pc.append(pairs[i][2])
        i += 1
    return i, pc


num_of_PC, cumsum = cumulative_constant(cumulative_sum, eig_pairs)
num_of_PC, cumsum

Scree Test via Sklearn PCA and bar plots

In [ ]:
# A simple line plot showing trends in PC's variances


def simple_scree_plot(pca):
    fig = plt.figure(figsize=(20, 20))
    ax = fig.add_subplot()
    ax.plot(np.cumsum(pca.explained_variance_ratio_))
    
    ax.set_xlabel('number of components')
    ax.set_ylabel('cumulative explained variance')
    
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    
    ax.tick_params(axis='x', colors='white')
    ax.tick_params(axis='y', colors='white')
    
    plt.show()


In [ ]:
# A scree bar plot showing contribution of components in the data


def scree_plot(pca):
    
    num_of_components = len(pca.explained_variance_ratio_)
    index = np.arange(num_of_components)
    values = pca.explained_variance_ratio_
    
    plt.figure(figsize=(20, 10))
    ax = plt.subplot(111)
    cumulative = np.cumsum(values)
    
    ax.bar(index, cumulative)
    ax.plot(index, cumulative)
    
    for i in range(num_of_components):
        ax.annotate(r'%s' % (str(values[i]*100)[:3]), (index[i], values[i]), 
                    va='bottom', ha='center', fontsize=14)
    ax.set_xlabel('Principal component number')
    ax.set_ylabel('Variance Explained Percentage')
    
    ax.xaxis.label.set_color('white')
    ax.yaxis.label.set_color('white')
    
    ax.tick_params(axis='x', colors='white')
    ax.tick_params(axis='y', colors='white')
    
    plt.title('Scree Plot for Payloads Frequency')


In [ ]:
# Function to generate PCA using the features matrix
# It uses sklearn library PCA definition
# Returns the PCA object


def cal_pca(features_data):
    pca = PCA(30)
    pca.fit_transform(features_data)
    return pca


pca = cal_pca(features_frequency)


In [ ]:
simple_scree_plot(pca)


In [ ]:
scree_plot(pca)

In [41]:
compressed_SVD = TruncatedSVD(30)
compressed_data = compressed_SVD.fit_transform(features_frequency)
pd.DataFrame(compressed_SVD.components_)

0             1             2             3             4    \
0   1.109332e-20  3.540121e-24 -2.434385e-25  2.359862e-25 -3.824219e-26   
1  -2.828969e-18  3.586693e-21 -3.169555e-22  9.201621e-24 -5.533152e-24   
2   2.346268e-18 -2.634820e-17  5.215807e-19 -3.125998e-19  7.703857e-20   
3  -3.089175e-18  1.363630e-17 -8.904945e-17 -8.705111e-18  3.950295e-19   
4  -7.273205e-19  5.680708e-17 -5.180852e-17 -5.432916e-17  1.245006e-17   
5   1.218547e-18  1.516178e-17  1.258482e-16 -2.551545e-17 -6.895174e-18   
6   2.778697e-18  9.848025e-17  3.154500e-17  2.036532e-17 -6.367067e-18   
7   2.514318e-20  1.543398e-17  3.508627e-17 -2.169198e-17 -4.571753e-17   
8  -1.315366e-18 -2.259590e-17  4.592974e-17  3.802239e-17  5.356991e-17   
9   8.804585e-19  5.294439e-18  1.344817e-17  4.906101e-17  2.578137e-17   
10 -2.706427e-18 -4.154758e-17 -2.368755e-17  3.131542e-17 -5.929370e-18   
11  1.315546e-18 -2.232423e-17 -8.999473e-18 -6.774430e-17  1.232519e-17   
12  2.359468e-19  2.825927e-17  5.803317e-17 -3.010998e-17 -4.184922e-17   
13 -6.770856e-19  8.717852e-19  3.114516e-17  4.744065e-17 -4.583455e-17   
14 -1.459919e-18 -1.315624e-17  2.911567e-17  4.299396e-17  6.032338e-17   
15 -5.817779e-20  5.005644e-17  4.038519e-17  5.756026e-18  2.972282e-17   
16  3.738510e-18  2.939329e-17 -4.846291e-17 -3.418614e-17 -7.646750e-17   
17  1.577405e-18  6.174857e-17  2.509213e-18  6.515245e-18 -4.460417e-17   
18 -1.746225e-18 -7.243509e-17  3.853121e-17 -1.314291e-17 -2.634907e-17   
19  2.029411e-18  3.121388e-17 -3.768237e-17 -1.237486e-17 -8.081442e-18   
20  4.974766e-19 -5.269624e-17 -3.287349e-17 -2.041604e-17 -6.687638e-17   
21  2.291374e-18  2.547866e-17 -4.201864e-17 -6.021528e-18 -3.183129e-17   
22 -1.496944e-18  3.015083e-17  5.424418e-17  1.279427e-17 -1.043680e-17   
23 -1.104407e-18 -6.146070e-17 -7.511220e-17  3.867978e-17 -1.406117e-17   
24 -2.696042e-18 -6.156155e-18  5.281324e-17 -9.944162e-19  1.838319e-17   
25 -2.658377e-18 -5.296815e-17 -3.152872e-17  2.618754e-17 -4.007752e-17   
26  2.421779e-18  6.266330e-17  4.624151e-17 -8.749350e-18  1.767534e-17   
27  6.813727e-19  2.015022e-17 -2.047287e-17 -2.152815e-17  3.254910e-17   
28  2.425747e-18  8.021118e-17 -1.550769e-18 -8.500702e-18 -2.698762e-17   
29 -1.146068e-18 -2.151355e-17 -1.697873e-18  9.146411e-18 -7.551239e-17   

             5             6             7             8             9    ...  \
0   1.526491e-27  5.466760e-27 -2.506744e-27  1.585636e-27  6.013041e-29  ...   
1   1.022110e-24  1.329416e-24  7.008335e-26 -7.175486e-26 -1.035228e-25  ...   
2  -6.622996e-21  1.381852e-20  9.527467e-21 -4.010586e-21  9.167268e-23  ...   
3  -6.886886e-21  2.050098e-19  1.131803e-19 -6.403641e-20 -1.071556e-20  ...   
4  -4.667418e-19 -5.950828e-19 -3.766330e-19  2.040574e-19 -1.410483e-19  ...   
5  -2.901324e-20 -5.369901e-18  8.213960e-19 -1.184280e-18  2.159977e-19  ...   
6  -3.318020e-17  3.748628e-17  2.751437e-18 -6.340147e-19  1.427305e-18  ...   
7  -2.305632e-17 -4.457057e-17 -4.757494e-17  1.998885e-17 -2.049352e-18  ...   
8   1.196153e-17 -1.506966e-17 -3.534572e-17  1.588358e-17 -7.085110e-18  ...   
9   1.567750e-17  2.881152e-18 -6.622481e-17  4.375945e-17 -1.802237e-18  ...   
10  5.535295e-18  1.874939e-17 -6.917329e-17 -9.000356e-18  1.914876e-17  ...   
11  7.635365e-17 -1.781145e-18 -8.464093e-18 -3.966256e-17 -2.448347e-17  ...   
12  1.588262e-17 -1.397559e-17 -4.263732e-18 -4.630223e-18  2.642750e-18  ...   
13 -1.224742e-17  4.540968e-17 -1.815536e-17 -1.969959e-17  4.496270e-17  ...   
14  1.340394e-17  2.823471e-17  8.009876e-18  1.033339e-17  1.723704e-17  ...   
15 -2.274690e-17 -2.762644e-17 -2.369330e-17 -7.033488e-18  3.776242e-17  ...   
16  1.029944e-17 -1.167688e-18 -1.797203e-17  1.979635e-17 -2.950319e-18  ...   
17 -2.300393e-17  2.214367e-17 -3.003005e-17  1.066071e-17  1.585583e-17  ...   
18  2.420715e-17  2.706784e-17 -2.839148e-17  8.265157e-18  1.622010e-17  ...   
19  8.672473e-18 -1.939542e-17 -5.86

In [12]:
compressed_SVD.explained_variance_ratio_

array([3.7437128 , 0.33433089, 0.37608431, 0.23053849, 0.20311546,
       0.16532139, 0.11362129, 0.10462727, 0.10063692, 0.08713229,
       0.07635089, 0.0631516 , 0.05515907, 0.0523507 , 0.04016385,
       0.03904492, 0.03610638, 0.0340988 , 0.03253479, 0.03089397,
       0.02946278, 0.0263502 , 0.02544903, 0.02293572, 0.01981963,
       0.01918852, 0.01711988, 0.01426646, 0.01314757, 0.00922638])

In [13]:
compressed_SVD.explained_variance_

array([0.09802568, 0.00875415, 0.00984742, 0.00603644, 0.00531839,
       0.00432879, 0.00297507, 0.00273957, 0.00263509, 0.00228148,
       0.00199918, 0.00165357, 0.00144429, 0.00137076, 0.00105165,
       0.00102236, 0.00094541, 0.00089285, 0.00085189, 0.00080893,
       0.00077146, 0.00068996, 0.00066636, 0.00060055, 0.00051896,
       0.00050243, 0.00044827, 0.00037355, 0.00034426, 0.00024158])

In [14]:
np.sum(compressed_SVD.explained_variance_)

0.16014033350581877

In [15]:
pd.DataFrame(compressed_data)

0         1         2         3         4         5         6   \
0       0.005446  0.251554 -0.077316 -0.003824  0.059662 -0.024499  0.024644   
1       0.006165  0.283481 -0.080622 -0.007703  0.056432  0.033775 -0.025597   
2       0.006474  0.267162 -0.001570  0.070406 -0.154439  0.006584 -0.052697   
3       0.006093  0.266574 -0.082303 -0.069123 -0.111201  0.136237  0.004872   
4       0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
5       0.005758  0.272508 -0.106794 -0.051524  0.131908  0.049253 -0.100457   
6       0.005232  0.195347  0.055154  0.105189  0.018723 -0.054673  0.009848   
7       0.056558  0.078666  0.165198 -0.143689 -0.026841 -0.073916  0.026354   
8       0.005100  0.208822  0.010035  0.072686 -0.090047 -0.020596  0.041746   
9       0.056748  0.084739  0.164430 -0.152003 -0.051219 -0.035903  0.042747   
10      0.005677  0.255774 -0.091667 -0.024797 -0.067370  0.053946 -0.123521   
11      0.005372  0.232435 -0.029500  0.055655  0.074596 -0.046469 -0.101071   
12      0.005495  0.247413 -0.025621  0.129678 -0.016833 -0.079598 -0.004066   
13      0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
14      0.052651  0.144054  0.017046 -0.043505  0.011610 -0.055324 -0.089962   
15      0.005837  0.239903  0.012109  0.069475 -0.132183  0.042127 -0.010297   
16      0.004650  0.205880 -0.102399 -0.039024  0.056437 -0.090262  0.032186   
17      0.004796  0.153529  0.045273  0.026650 -0.012655 -0.025226  0.031583   
18      0.005549  0.258095 -0.103309 -0.042785  0.012212  0.015521  0.065927   
19      0.006495  0.261940 -0.002109  0.043811 -0.131885  0.014802 -0.057413   
20      0.005350  0.189751  0.002768  0.014893  0.105036 -0.114136  0.132743   
21      0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
22      0.006724  0.267937 -0.076337 -0.092458 -0.143309  0.089944  0.112732   
23      0.156011  0.075858  0.150512 -0.129891 -0.031377 -0.037790  0.032142   
24      0.005993  0.254733 -0.055548  0.021199 -0.013672 -0.048647  0.014107   
25      0.206668  0.204457  0.014872 -0.082225  0.009134  0.002469 -0.061739   
26      0.005758  0.272508 -0.106794 -0.051524  0.131908  0.049253 -0.100457   
27      0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
28      0.005805  0.271886 -0.069182  0.041366  0.019545 -0.019206  0.042893   
29      0.056668  0.081345  0.153493 -0.153176 -0.055367 -0.044404  0.051598   
...          ...       ...       ...       ...       ...       ...       ...   
223555  0.005381  0.185623  0.009768 -0.009640 -0.067487  0.008231 -0.082621   
223556  0.005305  0.200530  0.008111  0.034387  0.117438 -0.085273  0.189848   
223557  0.050610  0.174585  0.015778 -0.050493 -0.038408 -0.040316 -0.003229   
223558  0.006165  0.283481 -0.080622 -0.007703  0.056432  0.033775 -0.025597   
223559  0.005339  0.204311  0.050630  0.090002  0.035400 -0.026708  0.004983   
223560  0.005313  0.238964 -0.050226  0.047244  0.051670 -0.025460 -0.025726   
223561  0.005828  0.210235  0.044752  0.046326  0.037365 -0.043366 -0.061460   
223562  0.005758  0.272508 -0.106794 -0.051524  0.131908  0.049253 -0.100457   
223563  0.033650  0.183495 -0.034206  0.034011  0.044464 -0.040618  0.048114   
223564  0.005446  0.251554 -0.077316 -0.003824  0.059662 -0.024499  0.024644   
223565  0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
223566  0.044753  0.184202  0.016769  0.068515  0.041674 -0.045879  0.035126   
223567  0.005824  0.225261 -0.013230  0.058322 -0.192350 -0.034605 -0.087261   
223568  0.005304  0.244724 -0.026693  0.101281 -0.040422  0.005738 -0.117785   
223569  0.999452 -0.026655 -0.015377  0.010428  0.001942  0.005305  0.000483   
223570  0.005313  0.238313 -0.034739  0.066898  0.044168 -0.038733 -0.026527   
223571  0.006093  0.266574 -0.082303 -0.069123 -0.111201  0.136237  0.004872   
223572  0.235733  0.100149  0.129423 -0.036425  0.037263  0.023365  0.065843   
223573  0.0061

In [16]:
sum_of_pcs = np.sum(compressed_data, axis=0)

In [ ]:
for x in sum_of_pcs:
  print(x)

In [21]:
compressed_data.shape

(223585, 30)

In [42]:
def calc_mean(frequency_vectors):
    return np.mean(frequency_vectors, axis=0)

features_reduced_mean = calc_mean(compressed_data)
features_reduced_mean.shape

(30,)

In [43]:
def calc_sd(features_frequency):
    return np.std(features_frequency, axis=0)

features_reduced_sd = calc_sd(compressed_data)
features_reduced_sd.shape

(30,)

In [44]:
def format_freq():
    features = np.transpose(compressed_data)
    covs = np.array([], dtype=np.float16)
    return np.append(covs, [cal_covariance(x) for x in features])

def cal_covariance(feature):
    feature_vector = np.array([feature, feature])
    result = np.matmul(feature_vector, np.transpose(feature_vector))
    return result[0][0]

covariances = format_freq()


In [25]:
covariances

array([25956.58905232,  9642.17859005,  2248.2587503 ,  1358.43141829,
        1189.59127805,   978.76991892,   665.34480995,   612.57843095,
         589.43469374,   510.13025381,   448.32775332,   369.80686996,
         323.27152272,   306.52637941,   235.24492415,   228.61571637,
         211.44021996,   199.6273395 ,   190.47640888,   180.86633031,
         172.48596537,   154.27170956,   149.0205592 ,   134.30529449,
         116.07034189,   112.33858611,   100.23426948,    83.53392636,
          76.98609397,    54.02437048])

In [45]:
np.square(features_reduced_sd)

array([0.09802568, 0.00875415, 0.00984742, 0.00603644, 0.00531839,
       0.00432879, 0.00297507, 0.00273957, 0.00263509, 0.00228148,
       0.00199918, 0.00165357, 0.00144429, 0.00137076, 0.00105165,
       0.00102236, 0.00094541, 0.00089285, 0.00085189, 0.00080893,
       0.00077146, 0.00068996, 0.00066636, 0.00060055, 0.00051896,
       0.00050243, 0.00044827, 0.00037355, 0.00034426, 0.00024158])

In [46]:
def calc_mahalanobis_dist(feature_x1, feature_x2, cov_x1, cov_x2):
    feature_diff = feature_x1-feature_x2
    feature_diff = feature_diff*np.transpose(feature_diff)
    if cov_x1+cov_x2 == 0:
        return 0
    return feature_diff/(cov_x1+cov_x2)
  

In [47]:
def construct_mdm(features):
    mdm = []
    i=0
    for index, feature1 in enumerate(features):
        feature_map = []
        for index2, feature2 in enumerate(features):
            feature_map.append(calc_mahalanobis_dist(feature1, feature2, covariances[index], covariances[index2]))
        mdm.append(feature_map)
    return np.array(mdm)

payload_map = np.array([construct_mdm(x) for x in compressed_data[:10000]])


In [ ]:
print("Payload map size: %d bytes" % (payload_map.size * payload_map.itemsize))

Payload map size: 72000000 bytes


In [ ]:
payload_map.shape

(10000, 30, 30)

In [ ]:
payload_map[0]

In [48]:
payloads_map_mean = np.mean(payload_map, axis=0)
payloads_map_mean.shape

(30, 30)

In [49]:
payloads_map_sd = np.std(payload_map, axis=0)
payloads_map_sd.shape

(30, 30)

In [50]:
payloads_map_variances = np.square(payloads_map_sd)
payloads_map_variances.shape

(30, 30)

In [54]:
payloads_map_variances

array([[0.00000000e+00, 8.30376269e-11, 1.35016179e-10, 1.29381630e-10,
        1.36133220e-10, 1.36505013e-10, 1.43226467e-10, 1.43212796e-10,
        1.43993864e-10, 1.44526132e-10, 1.46446901e-10, 1.47532954e-10,
        1.48219784e-10, 1.47763327e-10, 1.49120712e-10, 1.49093673e-10,
        1.49069782e-10, 1.49332478e-10, 1.49588081e-10, 1.49384033e-10,
        1.49810756e-10, 1.49510784e-10, 1.49786081e-10, 1.50313494e-10,
        1.50422020e-10, 1.50411160e-10, 1.50544933e-10, 1.50704000e-10,
        1.51140490e-10, 1.51116406e-10],
       [8.30376269e-11, 0.00000000e+00, 1.90946681e-11, 1.31650837e-11,
        1.78157165e-11, 8.17713618e-12, 1.28727491e-11, 1.13177929e-11,
        1.30016428e-11, 9.70880520e-12, 1.20795843e-11, 9.72579298e-12,
        7.96123517e-12, 8.95570439e-12, 8.16975876e-12, 7.34161687e-12,
        9.23676256e-12, 7.11011141e-12, 6.84279464e-12, 7.04255351e-12,
        6.76539086e-12, 8.02283871e-12, 8.31077932e-12, 8.20168583e-12,
        8.42735900e-12,

In [ ]:
def construct_payload_map(payload):
  vectorized = vectorize_payload(payload)
  payload_frequency = calc_frequency(vectorized)
  payload_mean = calc_mean(payload_frequency)
  payload_sd = np.std(payload_frequency)
  mean_shift = np.transpose(np.subtract(features_frequency, features_mean))    
  payload_cov_mat = np.cov(mean_shift)
  print(payload_cov_mat)

In [51]:
real_payload_map = construct_mdm(compressed_data[130000])

In [52]:
real_payload_map.shape

(30, 30)

In [53]:
def cal_weight(real_payload_map):
  return (np.square(real_payload_map - payloads_map_mean)/payloads_map_variances)

payload_weight = cal_weight(real_payload_map)
payload_weight

/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in divide
  


array([[       nan, 7.54262303, 7.56200619, 7.54763418, 7.56542273,
        7.5609581 , 7.56563377, 7.56704978, 7.5690074 , 7.56699655,
        7.56871227, 7.56905498, 7.57138578, 7.5693801 , 7.56744445,
        7.56835888, 7.56944343, 7.56834489, 7.568262  , 7.56781634,
        7.5690603 , 7.56977957, 7.57113765, 7.57079044, 7.57081862,
        7.57047026, 7.57150587, 7.57087274, 7.5716803 , 7.57102416],
       [7.54262303,        nan, 1.03841974, 1.44197082, 1.10209907,
        2.31195844, 1.51240596, 1.70417053, 1.49319293, 2.00869271,
        1.60812798, 1.97671928, 2.42633433, 2.16073828, 2.36686418,
        2.64486902, 2.10670379, 2.70589339, 2.82454541, 2.76592258,
        2.86816723, 2.40451552, 2.30454788, 2.35706526, 2.28875733,
        2.43546944, 2.49674888, 2.51103536, 2.4881386 , 2.58466722],
       [7.56200619, 1.03841974,        nan, 0.29035386, 0.63643997,
        0.57157836, 0.42829748, 0.3290314 , 0.41348444, 0.32006061,
        0.43383061, 0.29635568, 0.39672482, 0.